import Header from "./_components/Header"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header></Header>
        <div>
          <main>
            {children}
          </main>
        </div>
      </body>
    </html>
  )
}
